function [fitresult, gof] = createFit(Histogram)
%CREATEFIT(HISTOGRAM)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      Y Output: Histogram
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 11-Oct-2013 18:31:49


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( [], Histogram );

% Set up fittype and options.
ft = fittype( 'gauss2' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0 -Inf -Inf 0];
opts.StartPoint = [1725 203 14.2547592261289 491 7 29.5293526834364];
opts.Upper = [Inf Inf Inf Inf Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'Histogram', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
ylabel( 'Histogram' );
grid on


